import React from 'react';
import { ShieldCheck, Lock, Eye, UserCheck, Scale, KeyRound, Sparkles } from 'lucide-react';

export const ResponsibleAIPage: React.FC = () => {
  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 sm:py-12 space-y-10 animate-fade-in text-left">
      <div className="text-center max-w-3xl mx-auto space-y-3">
        <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-emerald-500/10 text-emerald-300 border border-emerald-500/30 text-xs font-mono font-bold shadow-sm">
          <ShieldCheck className="w-3.5 h-3.5 text-emerald-400" />
          <span>ETHICAL AI, PRIVACY BY DESIGN &amp; DPI GOVERNANCE</span>
        </div>
        <h1 className="text-3xl sm:text-4xl font-heading font-black text-white">
          Responsible AI &amp; Privacy Charter
        </h1>
        <p className="text-xs sm:text-sm text-slate-300 leading-relaxed font-medium">
          How JanNiti AI protects citizen confidentiality, eliminates personally identifiable information (PII), ensures algorithmic explainability, and enforces human-in-the-loop decision primacy.
        </p>
      </div>

      {/* Core Governance Pillars */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {/* Pillar 1 */}
        <div className="p-6 rounded-3xl bg-slate-900 border border-slate-800 shadow-xl space-y-3">
          <div className="w-12 h-12 rounded-2xl bg-blue-500/10 text-cyan-400 flex items-center justify-center border border-cyan-500/20">
            <UserCheck className="w-6 h-6" />
          </div>
          <h3 className="font-heading font-black text-sm text-white">
            1. Advisory Nature &amp; Human Primacy
          </h3>
          <p className="text-xs text-slate-400 leading-relaxed font-medium">
            All AI-generated priority rankings and project recommendations generated by Google Gemini serve strictly as <strong className="text-slate-200">decision-support advisories</strong>. Democratic representatives, District Magistrates, and departmental engineers retain sovereign statutory authority over final sanctions and budget outlays.
          </p>
        </div>

        {/* Pillar 2 */}
        <div className="p-6 rounded-3xl bg-slate-900 border border-slate-800 shadow-xl space-y-3">
          <div className="w-12 h-12 rounded-2xl bg-emerald-500/10 text-emerald-400 flex items-center justify-center border border-emerald-500/20">
            <Lock className="w-6 h-6" />
          </div>
          <h3 className="font-heading font-black text-sm text-white">
            2. Privacy by Design (Zero PII Mandate)
          </h3>
          <p className="text-xs text-slate-400 leading-relaxed font-medium">
            JanNiti AI <strong className="text-slate-200">never solicits or stores Aadhaar numbers, PAN cards, phone credentials, or biometric identifiers</strong>. Submissions are processed with anonymous tokens, capturing only spatial need coordinates and infrastructure deficit taxonomy.
          </p>
        </div>

        {/* Pillar 3 */}
        <div className="p-6 rounded-3xl bg-slate-900 border border-slate-800 shadow-xl space-y-3">
          <div className="w-12 h-12 rounded-2xl bg-purple-500/10 text-purple-400 flex items-center justify-center border border-purple-500/20">
            <Eye className="w-6 h-6" />
          </div>
          <h3 className="font-heading font-black text-sm text-white">
            3. Transparent &amp; Auditable Explainability
          </h3>
          <p className="text-xs text-slate-400 leading-relaxed font-medium">
            No black-box prioritization. Every priority score (0–100) publishes a six-factor mathematical breakdown (Urgency, Affected Population, Baseline Gap, Vulnerability, Spatial Density, Public Impact) with human-auditable justification statements.
          </p>
        </div>
      </div>

      {/* Detailed Privacy Notice */}
      <div className="p-7 sm:p-9 rounded-3xl bg-slate-900/90 text-white border border-slate-800 shadow-2xl space-y-4">
        <div className="flex items-center gap-2.5">
          <ShieldCheck className="w-6 h-6 text-emerald-400" />
          <h3 className="text-lg font-heading font-black">Public Privacy &amp; Data Protection Statement</h3>
        </div>
        <div className="space-y-3 text-xs text-slate-300 leading-relaxed">
          <p>
            • <strong className="text-white">Data Minimization:</strong> Only geographical location (village/district) and the substantive content of the public works request are recorded.
          </p>
          <p>
            • <strong className="text-white">Automated Redaction:</strong> When voice recordings or text statements are processed via Google Gemini, regex and entity-recognition filters automatically strip accidental names or phone numbers prior to analytical clustering.
          </p>
          <p>
            • <strong className="text-white">Server-side Key Protection:</strong> All AI inference calls are mediated server-side in compliance with Indian Digital Personal Data Protection (DPDP) Act guidelines. No API credentials or secret keys are exposed client-side.
          </p>
          <p>
            • <strong className="text-white">Fairness &amp; Linguistic Equity:</strong> Equal priority weighting is applied across all 10 supported Indian linguistic scripts without dialectal degradation or urban-only prioritization bias.
          </p>
        </div>
      </div>
    </div>
  );
};
